[package]
name = "linux-apex"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
apex-hal = { path = "../apex_rs" }


# Required
nix = "0.24"
anyhow = "1.0"
tempfile = "3.3"
clone3 = "0.2"
ipc-channel = { version = "0.16", features = [ "memfd" ] }
serde = { version = "1.0", features = ["derive"] }
libc = "0.2"

# Not yet used but may should
smol = "1.2"
hotwatch = "0.4"
fslock = "0.2"
notify = "4.0"

# Temporal
procfs = "0.13"
raw_sync = "0.1"
shared_memory = "0.12"
futures = "0.3"

[[example]]
name = "hello"