[workspace]
resolver = "2"

members = [
    "hypervisor",
    "partition",
    "core",

    "examples/hello_part",

    "examples/fuel_tank_simulation",
    "examples/fuel_tank_controller",

    "examples/ping_client",
    "examples/ping_server",

    "examples/dev_random",

    "examples/crypto_agility_crypto_part",
    "examples/crypto_agility_sender",
    "examples/crypto_agility_receiver",
]

[workspace.dependencies]
a653rs = "0.3.2"
log = "0"

# TODO remove this once there is a release **after** v0.10.0
# that includes https://github.com/rozbb/rust-hpke/pull/43
[patch.crates-io]
hpke = { git = "https://github.com/rozbb/rust-hpke" }