[workspace]

members = [
    "hypervisor",
    "partition",
    "core",

    "examples/hello_part",

    "examples/fuel_tank_simulation",
    "examples/fuel_tank_controller",

    "examples/ping_client",
    "examples/ping_server",

    "examples/dev_random",
]

[workspace.dependencies]
a653rs = "0.3.2"
log = "0"