[package]
name = "linux-apex-core"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
# TODO add features:
# - hypervisor
# - partition
# doing so, we can be more fine-grained with our dependencies (especially tokio)

[dependencies]
apex-rs = { git = "https://github.com/aeronautical-informatics/apex-rs.git", branch = "main" }
#apex-hal = { path = "../../apex_rs", features = ["p4", "serde"] }
nix = "0.25"
anyhow = "1.0"
procfs = "0.14"
itertools = "0.10"
log = "0"
walkdir = "2.3"
polling = "2.2"
serde = { version = "1.0", features = ["derive"] }
memmap2 = "0.5.5"
memfd = "0.6"
bincode = "1.3"
thiserror = "1.0"
bytesize = {version = "1.1.0", features = ["serde"]}
tokio = {version = "1.26", features = ["full"]}

[dev-dependencies]
rand = "0.8.5"
criterion = {version = "0.4", features = ["async_tokio"]}

[[bench]]
name = "ptrace"
harness = false