[package]
name = "hello_part"
version = "0.1.0"
edition = "2021"
#forced-target = "x86_64-unknown-linux-musl"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
apex-rs = { git = "https://github.com/aeronautical-informatics/apex-rs.git", branch = "main" }
apex-rs-postcard = { git = "https://github.com/aeronautical-informatics/apex-rs-postcard.git", branch = "main" }
#apex-hal = { path = "../../../apex_rs", features = ["p4"] }
linux-apex-core = { path = "../../core" }
apex-rs-linux = { path = "../../partition" }
serde = "1.0"
procfs = "0.14"
log = "0"
nix = "0.25"
memmap2 = "0.5.5"
humantime = "2.1"
once_cell = "1.13"