[package]
name = "hello_part"
version = "0.1.0"
edition = "2021"
#forced-target = "x86_64-unknown-linux-musl"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
apex-hal = { path = "../../../apex_rs", features = ["p4"] }
linux-apex-core = { path = "../../core" }
linux-apex-partition = { path = "../../partition" }
procfs = "0.14"
log = "0"
pretty_env_logger = "0.4"
nix = "0.25"
log-panics = {version = "2.1", features = ["with-backtrace"]}
memmap2 = "0.5.5"
humantime = "2.1"