major_frame: 1s
partitions:
  - name: Foo
    duration: 10ms
    offset: 0ms
    period: 500ms
    image: target/x86_64-unknown-linux-musl/release/hello_part
  - name: Bar
    offset: 100ms
    duration: 10ms
    image: target/x86_64-unknown-linux-musl/release/hello_part
    period: 1s
