[package]
name = "linux-apex-partition"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
apex-hal = { path = "../../apex_rs", features = ["p4"] }
linux-apex-core = { path = "../core" }
lazy_static = "1.4"
anyhow = "1.0"
nix = "0.24"
polling = "2.2"
inotify = "0.10"
log = "0"
once_cell = "1.13"
memmap2 = "0.5.5"
safemem = "0.3"