name: Run checks

on:
  pull_request:
  push:
    branches: [main]

jobs:
  nix-checks:
    name: Run nix flake check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v22
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v12
        with:
          name: dlr-ft
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Nix Flake Check
        run: nix flake check
