name: Checks

on:
  pull_request:
  push:
    branches: [main]

jobs:
  nix-flake-check:
    name: Run nix flake check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v15
        with:
          name: dlr-ft
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Nix Flake Check
        run: nix flake check

  impure-checks:
    name: Run check ${{ matrix.check }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        check:
          - cargo clippy --all-features -- -D warnings
          - cargo clippy -- -D warnings
          - udeps
          - treefmt --fail-on-change
          - audit --deny warnings
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v15
        with:
          name: dlr-ft
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-${{ github.job }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Run check ${{ matrix.check }}
        run: nix develop --command ${{ matrix.check }}
