name: Example execution

on:
  pull_request:
  push:
    branches: [main]

jobs:
  run-example:
    name: Run hypervisor with example ${{ matrix.example }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        example:
          - hello_part
          - fuel_tank
    env:
      DURATION: 10s
      RUST_LOG: trace
    steps:
      - uses: actions/checkout@v2
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v4
      - name: Run the Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v1
      - name: Check CGroup
        run: systemd-run --user --scope cat /proc/self/cgroup
      - name: Run example ${{ matrix.example }}
        run: nix develop --command systemd-run-example-${{ matrix.example }} --duration $DURATION  

  checks:
    name: Run check ${{ matrix.check }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        check:
          - udeps
          - treefmt --fail-on-change
          - audit --deny warnings
    steps:
      - uses: actions/checkout@v2
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v4
      - name: Run the Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v1
      - name: Run check ${{ matrix.check }}
        run: nix develop --command ${{ matrix.check }}
