name: Example execution

on:
  pull_request:
  push:
    branches: [main]

jobs:
  run-hello-partition:
    name: Run hypervisor with example "hello"
    runs-on: ubuntu-latest
    env:
      DURATION: 10s
      RUST_LOG: trace
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixos-stable
          extra_nix_config: |
            experimental-features = nix-command flakes
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - name: Cache Nix store
        uses: actions/cache@v3
        id: nix-cache
        with:
          path: /tmp/nixcache
          key: nix-${{ runner.os }}
      - name: Import Nix store cache
        if: "steps.nix-cache.outputs.cache-hit == 'true'"
        run: nix copy --no-check-sigs --from /tmp/nixcache --all
      - name: Check Cgroup
        run: systemd-run --user --scope cat /proc/self/cgroup
      - name: Build devshell
        run: nix build .#devShells.x86_64-linux.default
      - name: Build partition
        run: nix develop -c cargo build -p hello_part --target x86_64-unknown-linux-musl --release
      - name: Upload Partition
        uses: actions/upload-artifact@v3
        with:
          name: hello_part
          path: target/x86_64-unknown-linux-musl/release/hello_part
      - name: Build hypervisor
        run: nix develop -c cargo build -p linux-apex-hypervisor --release
      - name: Upload Hypervisor
        uses: actions/upload-artifact@v3
        with:
          name: linux-apex-hypervisor
          path: target/release/linux-apex-hypervisor
      - name: Run example
        run: |
          nix develop -c systemd-run --user --scope -- \
            target/release/linux-apex-hypervisor --duration $DURATION \
            examples/hello_part/hypervisor_config.yaml
      - name: Export Nix store cache
        if: "steps.nix-cache.outputs.cache-hit != 'true'"
        run: |
          nix copy --no-check-sigs --to /tmp/nixcache \
            .#devShells.x86_64-linux.default
