name: Example execution

on:
  pull_request:
  push:
    branches: [main]

jobs:
  run-example:
    name: Run hypervisor with example ${{ matrix.example }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        example:
          - hello_part
          - fuel_tank
          - ping
          - dev_random
          - ping_queue
          - redirect_stdio
    env:
      DURATION: 10s
      RUST_LOG: trace
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v22
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v12
        with:
          name: dlr-ft
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-${{ github.job }}-${{ matrix.example }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Check CGroup
        run: systemd-run --user --scope cat /proc/self/cgroup
      - name: Run example ${{ matrix.example }}
        run: nix develop --command systemd-run-example-${{ matrix.example }} --duration $DURATION
