name: Example execution

on:
  pull_request:
  push:
    branches: [main]

jobs:
  run-hello-partition:
    name: Run hypervisor with example "hello"
    runs-on: ubuntu-latest
    env:
      DURATION: 10s
      RUST_LOG: trace
    steps:
      - uses: actions/checkout@v2
      - name: Check Cgroup
        run: systemd-run --user --scope cat /proc/self/cgroup
      - uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixos-stable
          extra_nix_config: |
            experimental-features = nix-command flakes
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - name: Build devshell
        run: nix build .#devShells.x86_64-linux.default
      - name: Build partition
        run: nix develop -c cargo build -p hello_part --target x86_64-unknown-linux-musl --release
      - name: Build hypervisor
        run: nix develop -c cargo build -p linux-apex-hypervisor --release
      - name: Run example
        run: |
          nix develop -c systemd-run --user --scope -- \
            target/release/linux-apex-hypervisor --duration $DURATION \
            examples/hello_part/hypervisor_config.yaml
